project:
  type: website

website:
  title: "ISSS626-GAA (Geospatial Analytics and Applications)"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1a: Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
        - text: "Hands-on Exercise 1b: Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
        - text: "Hands-on Exercise 2a: 1st Order Spatial Point Patterns Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
        - text: "Hands-on Exercise 2b: 2nd Order Spatial Point Patterns Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
        - text: "Hands-on Exercise 3: Network Constrained Spatial Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4: Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    right: 
      - text: Home
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fontsize: 1.0em
    toc-title: Table of Contents
    toc-depth: 4
    grid: 
      sidebar-width: 200px
      body-width: 850px
      margin-width: 300px

editor: source